"""RLM Budget Controller — reconciles token costs from rlm.completion() sub-calls.

RLM sub-calls happen INSIDE rlm.completion() and are NOT visible to the
normal BudgetTracker (which only tracks direct llm_client.call() invocations).
This controller provides a separate accounting layer for RLM recursive calls,
allowing the system to:
  1. Track total token spend including recursive sub-calls
  2. Surface rlm_tokens_total and rlm_cost_total in budget reports
  3. Enforce a combined budget ceiling across direct + RLM calls

Architectural note:
  This is a NEW file (not a modification of tracker.py). The RLM controller
  is intentionally separate from BudgetTracker to maintain a clean separation
  between primary LLM call accounting and recursive sub-call reconciliation.
  To get the full picture, combine both:

    from src.budget.tracker import budget_tracker
    from src.budget.controller import rlm_budget_controller

    total_cost = budget_tracker.total_cost_usd + rlm_budget_controller.rlm_cost_total

Usage::

    from src.budget.controller import rlm_budget_controller

    # Called by RLMLogger after each sub-call
    rlm_budget_controller.track_rlm_subcall(
        tokens_in=1200,
        tokens_out=800,
        model="openrouter/openai/o3-mini",
        cost_usd=0.0024,
    )

    # Reconciled summary (include in budget report)
    summary = rlm_budget_controller.summary()
    # {'rlm_subcall_count': 1, 'rlm_tokens_total': 2000, 'rlm_cost_total': 0.0024, ...}

    # Reset for a new document run
    rlm_budget_controller.reset()
"""
from __future__ import annotations

import logging
import threading
from dataclasses import dataclass, field
from typing import List

logger = logging.getLogger(__name__)


@dataclass
class _RLMSubcallRecord:
    """Immutable record of a single RLM sub-call token spend."""
    tokens_in: int
    tokens_out: int
    model: str
    cost_usd: float


class RLMBudgetController:
    """Thread-safe tracker for RLM recursive sub-call token and cost spend.

    RLM sub-calls are invisible to the normal BudgetTracker because they
    happen inside rlm.completion() without going through llm_client.call().
    This class captures and reconciles those costs as a separate accounting
    lane, then exposes them via summary() for inclusion in budget reports.

    Fields tracked:
        rlm_subcall_count:      number of recursive sub-calls invoked
        rlm_tokens_in_total:    total prompt tokens consumed by sub-calls
        rlm_tokens_out_total:   total completion tokens generated by sub-calls
        rlm_tokens_total:       rlm_tokens_in_total + rlm_tokens_out_total
        rlm_cost_total:         total USD cost of all RLM sub-calls

    Integration point:
        Call track_rlm_subcall() from the RLMLogger callback (defined in
        src/llm/rate_limiter.py) or from llm_client.call() after
        rlm.completion() returns usage metadata.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._records: List[_RLMSubcallRecord] = []
        self._rlm_tokens_in_total: int = 0
        self._rlm_tokens_out_total: int = 0
        self._rlm_cost_total: float = 0.0

    def track_rlm_subcall(
        self,
        tokens_in: int,
        tokens_out: int,
        model: str,
        cost_usd: float,
    ) -> None:
        """Record token and cost spend from a single RLM sub-call.

        Thread-safe. Called after each rlm.completion() sub-call to reconcile
        costs that are invisible to the normal BudgetTracker.

        Args:
            tokens_in:  Prompt tokens consumed by this sub-call.
            tokens_out: Completion tokens generated by this sub-call.
            model:      Provider-prefixed model string (e.g. "openrouter/openai/o3-mini").
            cost_usd:   Monetary cost in USD for this sub-call.
        """
        with self._lock:
            self._records.append(
                _RLMSubcallRecord(
                    tokens_in=tokens_in,
                    tokens_out=tokens_out,
                    model=model,
                    cost_usd=cost_usd,
                )
            )
            self._rlm_tokens_in_total += tokens_in
            self._rlm_tokens_out_total += tokens_out
            self._rlm_cost_total += cost_usd

        logger.debug(
            "RLM subcall tracked: model=%s in=%d out=%d cost=$%.6f "
            "(running: tokens=%d cost=$%.4f)",
            model, tokens_in, tokens_out, cost_usd,
            self._rlm_tokens_in_total + self._rlm_tokens_out_total,
            self._rlm_cost_total,
        )

    def summary(self) -> dict:
        """Return reconciled RLM budget summary dict.

        Include this in the main budget report alongside BudgetTracker.summary()
        to get the full picture of token and cost spend for a document run.

        Returns:
            Dict with keys:
              - rlm_subcall_count:    number of recursive sub-calls
              - rlm_tokens_in_total:  total prompt tokens
              - rlm_tokens_out_total: total completion tokens
              - rlm_tokens_total:     total tokens (in + out)
              - rlm_cost_total:       total USD cost (6 decimal precision)
        """
        with self._lock:
            return {
                "rlm_subcall_count":    len(self._records),
                "rlm_tokens_in_total":  self._rlm_tokens_in_total,
                "rlm_tokens_out_total": self._rlm_tokens_out_total,
                "rlm_tokens_total":     self._rlm_tokens_in_total + self._rlm_tokens_out_total,
                "rlm_cost_total":       round(self._rlm_cost_total, 6),
            }

    def reset(self) -> None:
        """Reset all RLM accounting. Call at the start of each new document run."""
        with self._lock:
            self._records.clear()
            self._rlm_tokens_in_total = 0
            self._rlm_tokens_out_total = 0
            self._rlm_cost_total = 0.0
        logger.info("RLM BudgetController: reset for new document run")

    @property
    def rlm_tokens_total(self) -> int:
        """Total tokens consumed by RLM sub-calls (prompt + completion)."""
        with self._lock:
            return self._rlm_tokens_in_total + self._rlm_tokens_out_total

    @property
    def rlm_cost_total(self) -> float:
        """Total USD cost accumulated from all RLM sub-calls."""
        with self._lock:
            return self._rlm_cost_total

    def __repr__(self) -> str:
        s = self.summary()
        return (
            f"RLMBudgetController("
            f"subcalls={s['rlm_subcall_count']}, "
            f"tokens={s['rlm_tokens_total']:,}, "
            f"cost=${s['rlm_cost_total']:.4f})"
        )


# ---------------------------------------------------------------------------
# Module-level singleton
# Usage: from src.budget.controller import rlm_budget_controller
# ---------------------------------------------------------------------------
rlm_budget_controller = RLMBudgetController()
