"""Publisher node (§5.22) — format and emit final document.

Assembles all approved sections into the final document,
applies formatting, and writes output files (Markdown + DOCX).
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

# Optional DOCX support
try:
    from docx import Document as DocxDocument
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    _HAS_DOCX = True
except ImportError:
    _HAS_DOCX = False
    logger.debug("python-docx not installed — DOCX output disabled")


def publisher_node(state: dict) -> dict:
    """Assemble and publish the final document.

    Returns:
        Partial state with ``published``, ``output_path``,
        ``output_formats``, and ``publish_metadata``.
    """
    approved = state.get("approved_sections", [])
    config = state.get("config", {})
    doc_id = state.get("doc_id", "default")
    topic = state.get("topic", config.get("topic", "Untitled Document"))
    output_formats = config.get("output_formats", ["markdown", "docx"])

    if not approved:
        logger.warning("Publisher: no approved sections to publish")
        return {"published": False}

    # ── Output directory ─────────────────────────────────────────────
    output_dir = Path("output") / doc_id
    output_dir.mkdir(parents=True, exist_ok=True)
    generated_files: list[str] = []

    # ── 1. Markdown ──────────────────────────────────────────────────
    sections_md = []
    for i, section in enumerate(approved):
        title = section.get("title", f"Section {i + 1}")
        content = section.get("content", section.get("draft", ""))
        sections_md.append(f"## {title}\n\n{content}")

    document = f"# {topic}\n\n" + "\n\n---\n\n".join(sections_md)

    if "markdown" in output_formats:
        doc_path = output_dir / "document.md"
        doc_path.write_text(document, encoding="utf-8")
        generated_files.append(str(doc_path))

    # ── 2. DOCX ──────────────────────────────────────────────────────
    docx_path = None
    if "docx" in output_formats and _HAS_DOCX:
        docx_path = _generate_docx(output_dir, topic, approved, state)
        if docx_path:
            generated_files.append(str(docx_path))

    # ── 3. Metadata ──────────────────────────────────────────────────
    metadata = {
        "doc_id": doc_id,
        "topic": topic,
        "sections": len(approved),
        "total_words": len(document.split()),
        "published_at": datetime.now(timezone.utc).isoformat(),
        "quality_preset": state.get("budget", {}).get("quality_preset", "balanced"),
        "total_cost": state.get("budget", {}).get("spent_dollars", 0),
        "qa_passed": state.get("qa_passed", False),
        "output_formats": [f for f in output_formats if f != "docx" or _HAS_DOCX],
        "generated_files": generated_files,
    }

    meta_path = output_dir / "metadata.json"
    meta_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    logger.info(
        "Publisher: wrote %d sections (%d words, $%.2f) → %s",
        len(approved), metadata["total_words"],
        metadata["total_cost"],
        ", ".join(generated_files),
    )

    return {
        "published": True,
        "output_path": generated_files[0] if generated_files else "",
        "output_formats": generated_files,
        "publish_metadata": metadata,
    }


# ── DOCX Generator ──────────────────────────────────────────────────────────

def _generate_docx(
    output_dir: Path,
    topic: str,
    sections: list[dict],
    state: dict,
) -> Path | None:
    """Generate a styled DOCX document."""
    try:
        doc = DocxDocument()

        # ── Title page ───────────────────────────────────────────────
        title_para = doc.add_paragraph()
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title_para.add_run(topic)
        title_run.bold = True
        title_run.font.size = Pt(28)
        title_run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)

        # Subtitle
        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub_run = subtitle.add_run(
            f"Generated by Deep Research System\n"
            f"{datetime.now(timezone.utc).strftime('%B %d, %Y')}"
        )
        sub_run.font.size = Pt(12)
        sub_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

        doc.add_page_break()

        # ── Sections ─────────────────────────────────────────────────
        for i, section in enumerate(sections):
            title = section.get("title", f"Section {i + 1}")
            content = section.get("content", section.get("draft", ""))

            # Section heading
            heading = doc.add_heading(title, level=2)
            heading.runs[0].font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)

            # Body paragraphs
            for para_text in content.split("\n\n"):
                para_text = para_text.strip()
                if not para_text:
                    continue
                p = doc.add_paragraph(para_text)
                p.paragraph_format.space_after = Pt(8)
                for run in p.runs:
                    run.font.size = Pt(11)
                    run.font.name = "Calibri"

            # Separator between sections (except last)
            if i < len(sections) - 1:
                doc.add_paragraph("─" * 40).alignment = WD_ALIGN_PARAGRAPH.CENTER

        # ── Save ─────────────────────────────────────────────────────
        docx_path = output_dir / "document.docx"
        doc.save(str(docx_path))
        logger.info("Publisher: DOCX written to %s", docx_path)
        return docx_path

    except Exception as exc:
        logger.warning("Publisher: DOCX generation failed: %s", exc)
        return None
